# Generated by Django 5.1.6 on 2025-04-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="name",
            new_name="username",
        ),
    ]
