# Generated by Django 5.1.6 on 2025-03-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("webapp", "0002_vote_election"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="voter_permissions", to="auth.permission"
            ),
        ),
    ]
