# Generated by Django 5.1.6 on 2025-03-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_voter_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="username",
        ),
    ]
