# Generated by Django 5.1.6 on 2025-02-24 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_candidate_election"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="age",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="name",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="otp_verified",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="status",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="username",
        ),
        migrations.AddField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.candidate",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
