# Generated by Django 5.1.6 on 2025-02-26 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_remove_vote_age_remove_vote_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Voter",
        ),
        migrations.RenameField(
            model_name="election",
            old_name="some_field",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.candidate"
            ),
        ),
    ]
