# Generated by Django 5.1.6 on 2025-02-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_rename_user_voter_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Voter",
        ),
    ]
