# Generated by Django 5.1.6 on 2025-02-27 13:33

import webapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_voter"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="voter",
            managers=[
                ("objects", webapp.models.VoterManager()),
            ],
        ),
    ]
